export const INCREMENT_INTEREST = 'INCREMENT_INTEREST';
export type INCREMENT_INTEREST = typeof INCREMENT_INTEREST;

export const DECREMENT_INTEREST = 'DECREMENT_INTEREST';
export type DECREMENT_INTEREST = typeof DECREMENT_INTEREST;
